before_script:
  - env
  - pwd
  - ls -al

stages:
  - dev-container-for-golang
  
dev-container-for-golang:
  image: harbor.ske.shein.io/base_images/docker:19.03.14-dind
  stage: dev-container-for-golang
  tags:
    - docker
    - image-burner
  rules:
  # tag: dev-container/golang/images/1.19/0.0.1
    - if: '$CI_COMMIT_TAG =~ /^dev-container\/golang.*$/'
      changes: 
      - dev-container/**/*
      when: on_success
  script:
    - IMAGE_VERSION=$(echo $CI_COMMIT_TAG | sed "s|/|$|g" | cut -d "$" -f 5)
    - GO_VERSION=$(echo $CI_COMMIT_TAG | sed "s|/|$|g" | cut -d "$" -f 4)
    - echo $IMAGE_VERSION
    - echo $GO_VERSION
    - make image.push.amd.golang GO_VERSION=$GO_VERSION IMAGE_VERSION=$IMAGE_VERSION IMAGE_REPO_ADDRESS="harbor.ske.shein.io/nocalhost/dev-container"
